# Generated by Django 5.2.11 on 2026-02-15 09:57

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Currency = apps.get_model("exchange", "Currency")
    Provider = apps.get_model("exchange", "Provider")

    # Currency data
    currencies = [
        {"code": "EUR", "name": "Euro", "symbol": "€"},
        {"code": "CHF", "name": "Swiss Franc", "symbol": "CHF"},
        {"code": "USD", "name": "US Dollar", "symbol": "$"},
        {"code": "GBP", "name": "British Pound", "symbol": "£"},
    ]

    for currency_data in currencies:
        Currency.objects.get_or_create(
            code=currency_data["code"],
            defaults={
                "name": currency_data["name"],
                "symbol": currency_data["symbol"]
            }
        )

    # Provider data
    providers = [
        {"name": "currency_beacon", "priority": 1, "is_active": True},
        {"name": "mock", "priority": 2, "is_active": True},
    ]

    for provider_data in providers:
        Provider.objects.update_or_create(
            name=provider_data["name"],
            defaults={
                "priority": provider_data["priority"],
                "is_active": provider_data["is_active"]
            }
        )


def reverse_initial_data(apps, schema_editor):
    Currency = apps.get_model("exchange", "Currency")
    Provider = apps.get_model("exchange", "Provider")

    Currency.objects.filter(code__in=["EUR", "CHF", "USD", "GBP"]).delete()
    Provider.objects.filter(name__in=["currency_beacon", "mock"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
